#!/bin/bash
cd `dirname $0`
/usr/bin/echo "=== Loading the latest housemech test script"
/usr/local/bin/housedepositor --group=mechtest scripts mechrules.tcl mechrules.tcl
/usr/bin/echo "=== Running housemech"
../housemech --http-debug --group=mechtest | tee ../donotcommit/mech.txt

